version: "3" 

services:
  db:
    image: mariadb:10.4.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pondel001
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:

  

